### PR TITLE
Loading 3D models and URDFs

### PR DESCRIPTION
**Pull request by azazdeaz**
Hi @wynss!

I started to hack-in model and URDF loading for a project. If you're interested in taking a pull request, i'd be happy to discuss how should i continue with this to make it more in-line with your plans for Kesko. Of course, i completely understand if you'd prefer to implement these features yourself. I saw that you're already working on URDF loading :star_struck: 
Screenshot from 2023-06-30 15-52-47

### CODE REVIEW

**Comment by wynss** [comment]
Hey! Really cool to see this! I appreciate all help I can get since my time is very limited at the moment. I will take a look at this when I get an empty time slot (hopefully soon but cannot promise anything) As you said I'm also looking into URDF support as one of the next steps. One goal for Kesko is that it should be very easy to control any robot from the python side and use it in an RL context.

**Comment by azazdeaz** [comment]
Sorry, this has grown into a mess, and we went into a different direction in the end, so i'm closing this. But your project is amazing, and i'm looking forward to your updates! :star_struck:

**Comment by wynss** [comment]
No worries, can probably at least take some inspiration going forward, thanks for that. Just being curious, was this exploration part of some bigger project or just for fun, I mean since you said "we"?

**Comment by azazdeaz** [comment]
Yes, exploration :) At https://github.com/art-e-fact, we are looking for a way to visualize SDF worlds and some other stuff in browsers. Kesko demonstrated that using Rust/Bevy, it's possible to build very nice things :)

**Pull request closed without merging**
